

pub const AvroError = error{
    SnappyCrc32,
    BoolValue,
    FixedValue,
    BytesValue,
    GetUuidFromStringValue,
    NameCollision,
    ResolveDecimalSchema,
    ConvertToUtf8,
    ConvertToUtf8Error,
    Validation,
    ValidationWithReason,
    MemoryAllocation,
    SignExtend,
    ReadBoolean,
    ReadBytes,
    ReadString,
    ReadDouble,
    ReadFloat,
    ReadDuration,
    ReadFixed,
    ConvertStrToUuid,
    MapKeyType,
    GetUnionVariant,
    EnumSymbolIndex,
    GetEnumSymbol,
    GetEnumUnknownIndexValue,
    GetScaleAndPrecision,
    GetScaleWithFixedSize,
    GetUuid,
    GetDecimalFixedBytes,
    ResolveDuration,
    ResolveDecimal,
    GetField,
    GetU8,
    ComparePrecisionAndSize,
    ConvertLengthToI32,
    GetDate,
    GetTimeMillis,
    GetTimeMicros,
    GetTimestampMillis,
    GetTimestampMicros,
    GetNull,
    GetBoolean,
    GetInt,
    GetLong,
    GetDouble,
    GetFloat,
    GetBytes,
    GetString,
    GetEnum,
    CompareFixedSizes,
    GetStringForFixed,
    GetEnumDefault,
    GetEnumValue,
    GetDecimalMetadataFromJson,
    FindUnionVariant,
    EmptyUnion,
    GetArray,
    GetMap,
    GetRecord,
    GetNameField,
    GetNameFieldFromRecord,
    GetNestedUnion,
    GetUnionDuplicate,
    GetDefaultUnion,
    GetU64FromJson,
    GetI64FromJson,
    ConvertU64ToUsize,
    ConvertU32ToUsize,
    ConvertI64ToUsize,
    ConvertI32ToUsize,
    GetPrecisionOrScaleFromJson,
    ParseSchemaJson,
    ParseSchemaFromValidJson,
    ParsePrimitive,
    GetDecimalMetadataValueFromJson,
    DecimalPrecisionLessThanScale,
    DecimalPrecisionMuBePositive,
    GetLogicalTypeVariant,
    GetLogicalTypeField,
    GetLogicalTypeFieldType,
    GetComplexType,
    GetComplexTypeField,
    GetRecordFieldsJson,
    GetEnumSymbolsField,
    GetEnumSymbols,
    EnumSymbolName,
    InvalidSchemaName,
    EnumSymbolDuplicate,
    GetArrayItemsField,
    GetMapValuesField,
    GetFixedSizeField,
    DeflateCompress,
    DeflateCompressFinish,
    DeflateDecompress,
    SnappyCompress,
    GetSnappyDecompressLen,
    SnappyDecompress,
    ZstdCompress,
    ZstdDecompress,
    ReadHeader,
    HeaderMagic,
    SingleObjectHeaderMismatch,
    GetAvroSchemaFromMap,
    GetHeaderMetadata,
    ReadBlockMarker,
    ReadIntoBuf,
    GetBlockMarker,
    IntegerOverflow,
    ReadVariableIntegerBytes,
    ZagI32,
    ReadBlock,
    SerializeValue,
    DeserializeValue,
    WriteBytes,
    WriteMarker,
    ConvertJsonToString,
    ConvertF64ToJson,
    SchemaResolutionError,
    FileHeaderAlreadyWritten,
    InvalidMetadataKey,
    AmbiguousSchemaDefinition,
    EncodeDecimalAsFixedError,
    NoEntryInLookupTable,
    EncodeValueAsSchemaError,
    IllegalSingleObjectWriterState,
    CodecNotSupported,
    BadCodecMetadata,
};

const Self = @This();

// fn failSnappyCrc32(self: *Self)



const std = @import("std");

// pub fn main() AvroError {
//     return error.SnappyCrc32;
// }


pub fn main() !void {

    const stdout = std.io.getStdOut().writer();
    // const testing = std.testing;
    try stdout.print("Array lenght {s}!\n", .{"toto"});
    return AvroError.SnappyCrc32;
}